{
 "title": "ECG QC performances",
 "time": { "from": "2021-02-15T00:18:35.318Z", "to": "2021-02-15T00:19:18.631Z" },
 "templating": {
  "list": [
   {
    "name": "pat",
    "label": "Patient (metrics)",
    "query": "select distinct patient from metrics order by patient asc"
   },
   {
    "name": "model",
    "label": "ECG QC model",
    "query": "select distinct model_ecg_qc from metrics "
   },
   {
    "name": "patecg",
    "label": "Patient (ECG)",
    "query": "SHOW TAG VALUES ON \"qrs\" FROM \"DetectedQRS\" WITH KEY = \"patient\""
   },
   {
    "name": "channel",
    "label": "Channel",
    "query": "SHOW TAG VALUES ON \"qrs\" FROM \"DetectedQRS\" WITH KEY = \"channel\""
   },
   {
    "name": "snr",
    "label": "SNR (dB)",
    "query": "SHOW TAG VALUES ON \"qrs\" FROM \"DetectedQRS\" WITH KEY = \"snr\""
   }
  ]
 },
 "panels": [
  {
   "title": "Positive predictivity",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select patient, snr, positive_predictivity from metrics where patient in ($pat) and model_ecg_qc in ($model) order by patient, snr asc\n"
    }
   ]
  },
  {
   "title": "Sensitivity",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select patient, snr, sensitivity from metrics where patient in ($pat) and model_ecg_qc in ($model) order by patient, snr asc\n"
    }
   ]
  },
  {
   "title": "F1-score",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "select patient, snr, f1_score from metrics where patient in ($pat) and model_ecg_qc in ($model) order by patient, snr asc\n"
    }
   ]
  },
  {
   "title": "Failure detection",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "select patient, snr, failure_detection from metrics where patient in ($pat) and model_ecg_qc in ($model) order by patient, snr asc\n"
    }
   ]
  },
  {
   "title": "ECG + Detected QRS (Hamilton)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Amplitude (mV)" }
   ],
   "targets": [
    {
     "alias": "ECG",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT amplitude FROM \"qrs\".\"autogen\".\"ECG\" where snr='$snr' and channel='$channel' and patient='$patecg' and $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}