version: '3.3'

services:

  influxdb:
    image: influxdb:1.8
    container_name: aura-influxdb
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DATABASE}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

  postgres:
    image: postgres:11
    container_name: aura-postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}

  grafana:
    image: grafana/grafana:7.3.4
    container_name: aura-grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./conf/provisioning:/etc/grafana/provisioning
      - ./conf/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - influxdb
      - postgres
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=natel-plotly-panel,michaeldmoore-scatter-panel,ae3e-plotly-panel

volumes:
  influxdb-storage:
  grafana-storage:
  postgres-storage:

