name: CI

on:
  # Triggers the workflow on push
  push:
    branches: '**'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    container: python:3.9.4-alpine3.13
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Lint
        run: flake8 dags/ test/

  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SAST 
        uses: returntocorp/semgrep-action@v1
        with:
          config: 'p/ci'
 
  unittests:
    runs-on: ubuntu-latest
    container: python:3.9.4-alpine3.13
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
          pip install -r requirements.txt
      - name: Unit tests
        run: python -m pytest test/

  build:
    needs: [lint, sast, unittests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name : print congrats 
        run : echo 'Build step has been reached ! Congrats !'
